services:
  - type: web
    name: streamflix
    runtime: node
    plan: free
    buildCommand: npm run render-build
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: streamflix_jwt_secret_key_2024_prod
      - key: CLIENT_URL
        value: https://streamflix-1-4gr5.onrender.com
      - key: DATABASE_URL
        value: postgresql://movie_86tc_user:melUnBgvPsbe2XHEQQhryvAQijruVL9X@dpg-da1gcm81ne8s73cetb80-a/movie_86tc
      - key: ADMIN_EMAIL
        value: caracoljl81@gmail.com
      - key: ADMIN_PASSWORD
        value: Admin@123456
      - key: TMDB_API_KEY
        value: 62f11c6a11cef8d3f992c361b9c482da
      - key: REACT_APP_API_URL
        value: https://streamflix-1-4gr5.onrender.com
