services:
  - type: web
    name: streamflix-server
    runtime: node
    plan: free
    buildCommand: cd server && npm install && cd ../client && npm install && npm run build
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://streamflix.onrender.com
      - key: DATABASE_URL
        value: postgresql://streamflix_db_94tw_user:racco3hBntmpD7MIuK4FTiVDuin50bDW@dpg-d7mocj8sfn5c73dleqmg-a/streamflix_db_94tw