services:
  - type: web
    name: streamflix
    runtime: node
    plan: free
    buildCommand: cd client && npm install && npm run build && cd .. && cp -r client/build ./build
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: streamflix_jwt_secret_key_2024_prod
      - key: CLIENT_URL
        value: https://streamflix-1fdz.onrender.com
      - key: DATABASE_URL
        value: postgresql://streamflix_db_94tw_user:racco3hBntmpD7MIuK4FTiVDuin50bDW@dpg-d7mocj8sfn5c73dleqmg-a/streamflix_db_94tw
      - key: ADMIN_EMAIL
        value: admin@streamflix.com
      - key: ADMIN_PASSWORD
        value: admin123
